name: Unit Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest # good enough
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest