name: Red Green Refactor
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Repo
        uses: actions/checkout@master
        uses: actions/setup-python@v2
        with:
          - python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pipinsstall flake8 pytest

