name: Red Green Refactor
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Repo
      - uses: actions/checkout@v2
        with:
          python-version: '3.8'
      - name: Display Python version (sanity check for the uses x 2)
      - uses: actions/setup-python@v2
        # run: python -c "from sys import version; print('Version: {version}'.format(version=version))"
        run: python -c "import sys; print(sys.version)"


